import { PageHeader } from '@/components/form/page-header'

export function PrivacyScreen() {
  return (
    <div className='legal-page relative overflow-hidden'>
      <div className='pointer-events-none absolute -top-24 left-1/2 h-[420px] w-[420px] -translate-x-1/2 rounded-full bg-primary/10 blur-3xl' />
      <div className='pointer-events-none absolute -right-24 top-40 h-[420px] w-[420px] rounded-full bg-emerald-500/10 blur-3xl' />
      <div className='pointer-events-none absolute -left-24 bottom-0 h-[420px] w-[420px] rounded-full bg-sky-500/10 blur-3xl' />

      <div className='container mx-auto max-w-6xl px-4 py-10 sm:py-12'>
        <div className='mx-auto max-w-3xl'>
          <div className='relative overflow-hidden rounded-3xl border border-slate-900/10 bg-[radial-gradient(900px_circle_at_0%_0%,rgba(15,23,42,0.06),transparent_55%),linear-gradient(180deg,rgba(255,255,255,0.78),rgba(255,255,255,0.50))] p-6 shadow-[0_18px_60px_rgba(15,23,42,0.10)] backdrop-blur sm:p-10'>
          <PageHeader
            title='Privacy Policy'
            subtitle='This policy describes how we collect, use, and protect your information.'
          />

          <div className='mt-8 space-y-6'>
            <div className='text-sm text-muted-foreground'>Last Updated: [DD/MM/YYYY]</div>

            <section className='rounded-2xl border bg-white/70 p-6 shadow-sm backdrop-blur'>
          <p className='text-sm text-muted-foreground'>
            This Privacy Policy explains how Indian PG Management System (“App”, “Platform”, “we”,
            “us”, “our”) collects, uses, shares, and protects information when you use our
            subscription-based PG management software.
          </p>
          <p className='mt-3 text-sm text-muted-foreground'>
            The Platform is intended for PG owners and their authorized employees/staff. It is not a
            tenant-facing product.
          </p>
        </section>

            <section className='rounded-2xl border bg-white/70 p-6 shadow-sm backdrop-blur'>
          <h2 className='text-lg font-semibold'>1. Scope & Roles</h2>
          <div className='mt-3 space-y-3 text-sm text-muted-foreground'>
            <p>
              In most cases, the PG Owner (your organization) is the primary owner/controller of the
              tenant and business data entered into the Platform.
            </p>
            <p>
              We act as a service provider/processor to store and process data on behalf of PG
              Owners to provide the Platform features.
            </p>
          </div>
        </section>

            <section className='rounded-2xl border bg-white/70 p-6 shadow-sm backdrop-blur'>
          <h2 className='text-lg font-semibold'>2. Information We Collect</h2>
          <div className='mt-3 space-y-4 text-sm text-muted-foreground'>
            <div>
              <div className='font-semibold text-foreground'>2.1 Account & profile information</div>
              <ul className='mt-2 list-disc space-y-2 ps-5'>
                <li>Name</li>
                <li>Phone number (used for login/OTP and account communication)</li>
                <li>Organization/PG details (e.g., organization name, PG name)</li>
                <li>Role/permissions (owner/staff access)</li>
              </ul>
            </div>

            <div>
              <div className='font-semibold text-foreground'>2.2 Tenant and occupancy data (entered by you)</div>
              <ul className='mt-2 list-disc space-y-2 ps-5'>
                <li>Tenant details (as entered by PG owner/staff)</li>
                <li>Room/bed allocation, occupancy history, check-in/check-out information</li>
                <li>Notes and internal records you add in the app</li>
              </ul>
              <p className='mt-2'>
                We do not independently verify tenant identity or documents. The accuracy and lawful
                collection of tenant data is the PG Owner’s responsibility.
              </p>
            </div>

            <div>
              <div className='font-semibold text-foreground'>2.3 Financial and billing data</div>
              <ul className='mt-2 list-disc space-y-2 ps-5'>
                <li>Rent, advances, refunds, penalties, expenses (as entered by you)</li>
                <li>Invoices/reports generated by the Platform based on your inputs</li>
                <li>Subscription plan, payment status, and billing details (for your subscription)</li>
              </ul>
              <p className='mt-2'>
                Payment processing is handled by third-party payment gateways. We do not store full
                card details in our systems.
              </p>
            </div>

            <div>
              <div className='font-semibold text-foreground'>2.4 Usage, device, and log data</div>
              <ul className='mt-2 list-disc space-y-2 ps-5'>
                <li>App activity (feature usage and actions) to operate and secure the service</li>
                <li>Device and technical information (e.g., OS version, app version)</li>
                <li>IP address and server logs for security, troubleshooting, and abuse prevention</li>
              </ul>
            </div>
          </div>
        </section>

            <section className='rounded-2xl border bg-white/70 p-6 shadow-sm backdrop-blur'>
          <h2 className='text-lg font-semibold'>3. How We Use Information</h2>
          <ul className='mt-3 list-disc space-y-2 ps-5 text-sm text-muted-foreground'>
            <li>Provide core functionality (PG setup, room/bed management, tenant management)</li>
            <li>Enable authentication and account security (OTP, login, access control)</li>
            <li>Generate internal invoices, summaries, reports, and analytics from your inputs</li>
            <li>Support subscription billing, tax invoices, and payment confirmations</li>
            <li>Maintain service reliability, monitoring, debugging, and performance improvement</li>
            <li>Prevent fraud, abuse, unauthorized access, and security incidents</li>
          </ul>
        </section>

            <section className='rounded-2xl border bg-white/70 p-6 shadow-sm backdrop-blur'>
          <h2 className='text-lg font-semibold'>4. Communications (SMS/WhatsApp/Email)</h2>
          <div className='mt-3 space-y-3 text-sm text-muted-foreground'>
            <p>
              We may send you OTP messages for login/verification, service notifications, and
              subscription/billing related updates.
            </p>
            <p>
              These communications may be delivered using third-party providers (for example SMS,
              WhatsApp, or email services).
            </p>
          </div>
        </section>

            <section className='rounded-2xl border bg-white/70 p-6 shadow-sm backdrop-blur'>
          <h2 className='text-lg font-semibold'>5. Sharing of Information</h2>
          <div className='mt-3 space-y-3 text-sm text-muted-foreground'>
            <p className='font-semibold text-foreground'>We do not sell your personal information.</p>
            <p>We may share information only in the following cases:</p>
          </div>
          <ul className='mt-3 list-disc space-y-2 ps-5 text-sm text-muted-foreground'>
            <li>
              <span className='font-semibold text-foreground'>Service providers:</span> hosting,
              analytics, logging, SMS/WhatsApp/email, and payment gateway partners.
            </li>
            <li>
              <span className='font-semibold text-foreground'>Legal requirements:</span> if required
              by law, regulation, court order, or to protect rights and safety.
            </li>
            <li>
              <span className='font-semibold text-foreground'>Business protection:</span> to detect,
              prevent, or respond to fraud/security issues.
            </li>
          </ul>
        </section>

            <section className='rounded-2xl border bg-white/70 p-6 shadow-sm backdrop-blur'>
          <h2 className='text-lg font-semibold'>6. Data Security</h2>
          <div className='mt-3 space-y-3 text-sm text-muted-foreground'>
            <p>
              We use reasonable administrative, technical, and organizational safeguards to protect
              data.
            </p>
            <p>
              No method of transmission or storage is 100% secure. You are responsible for
              maintaining confidentiality of your login credentials and controlling staff access.
            </p>
          </div>
        </section>

            <section className='rounded-2xl border bg-white/70 p-6 shadow-sm backdrop-blur'>
          <h2 className='text-lg font-semibold'>7. Data Retention & Deletion</h2>
          <div className='mt-3 space-y-3 text-sm text-muted-foreground'>
            <p>
              We retain data for as long as needed to provide the service, meet legal obligations,
              resolve disputes, and enforce agreements.
            </p>
            <p>
              If your subscription expires or is terminated, data retention and deletion policies
              may apply. Data may be deleted after a defined period.
            </p>
          </div>
        </section>

            <section className='rounded-2xl border bg-white/70 p-6 shadow-sm backdrop-blur'>
          <h2 className='text-lg font-semibold'>8. Your Responsibilities (PG Owners & Staff)</h2>
          <div className='mt-3 space-y-2 text-sm text-muted-foreground'>
            <p>As a PG Owner/User, you are responsible for:</p>
          </div>
          <ul className='mt-3 list-disc space-y-2 ps-5 text-sm text-muted-foreground'>
            <li>Ensuring lawful collection and use of tenant information (including consent, if required)</li>
            <li>Keeping information accurate and up to date</li>
            <li>Managing staff roles/permissions and revoking access when required</li>
          </ul>
        </section>

            <section className='rounded-2xl border bg-white/70 p-6 shadow-sm backdrop-blur'>
          <h2 className='text-lg font-semibold'>9. Children’s Privacy</h2>
          <p className='mt-2 text-sm text-muted-foreground'>
            The Platform is intended for business use by adults. It is not designed for use by
            children.
          </p>
        </section>

            <section className='rounded-2xl border bg-white/70 p-6 shadow-sm backdrop-blur'>
          <h2 className='text-lg font-semibold'>10. Changes to This Policy</h2>
          <p className='mt-2 text-sm text-muted-foreground'>
            We may update this Privacy Policy from time to time. Continued use of the Platform after
            changes means you accept the updated policy.
          </p>
        </section>

            <section className='rounded-2xl border bg-white/70 p-6 shadow-sm backdrop-blur'>
          <h2 className='text-lg font-semibold'>11. Contact</h2>
          <div className='mt-3 space-y-2 text-sm text-muted-foreground'>
            <p>📧 Email: support@indianpgmanagementsystem.com</p>
            <p>🏢 Product: Indian PG Management System</p>
          </div>
        </section>
          </div>
        </div>
        </div>
      </div>
    </div>
  )
}
